[2024-10-21T02:40:29.718+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_tickers_etl.transform scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-21T02:40:29.730+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_tickers_etl.transform scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-21T02:40:29.731+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-10-21T02:40:29.746+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2024-10-14 00:00:00+00:00
[2024-10-21T02:40:29.754+0000] {standard_task_runner.py:57} INFO - Started process 564 to run task
[2024-10-21T02:40:29.756+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_tickers_etl', 'transform', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '771', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmp_h5f11tx']
[2024-10-21T02:40:29.758+0000] {standard_task_runner.py:85} INFO - Job 771: Subtask transform
[2024-10-21T02:40:29.808+0000] {task_command.py:416} INFO - Running <TaskInstance: crypto_tickers_etl.transform scheduled__2024-10-14T00:00:00+00:00 [running]> on host 9ef7466b1d1e
[2024-10-21T02:40:29.892+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_tickers_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T00:00:00+00:00'
[2024-10-21T02:40:29.906+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_etl_dag.py", line 19, in transform_data
    tickers = data['tickers']
KeyError: 'tickers'
[2024-10-21T02:40:29.917+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_tickers_etl, task_id=transform, execution_date=20241014T000000, start_date=20241021T024029, end_date=20241021T024029
[2024-10-21T02:40:29.929+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 771 for task transform ('tickers'; 564)
[2024-10-21T02:40:29.970+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-21T02:40:29.997+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
