[2024-10-21T02:39:53.783+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_tickers_etl.transform scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-10-21T02:39:53.811+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_tickers_etl.transform scheduled__2024-09-16T00:00:00+00:00 [queued]>
[2024-10-21T02:39:53.812+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-10-21T02:39:53.864+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2024-09-16 00:00:00+00:00
[2024-10-21T02:39:53.894+0000] {standard_task_runner.py:57} INFO - Started process 402 to run task
[2024-10-21T02:39:53.955+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crypto_tickers_etl', 'transform', 'scheduled__2024-09-16T00:00:00+00:00', '--job-id', '713', '--raw', '--subdir', 'DAGS_FOLDER/crypto_etl_dag.py', '--cfg-path', '/tmp/tmptm3vofdy']
[2024-10-21T02:39:53.973+0000] {standard_task_runner.py:85} INFO - Job 713: Subtask transform
[2024-10-21T02:39:54.234+0000] {task_command.py:416} INFO - Running <TaskInstance: crypto_tickers_etl.transform scheduled__2024-09-16T00:00:00+00:00 [running]> on host 9ef7466b1d1e
[2024-10-21T02:39:54.650+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_tickers_etl' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-16T00:00:00+00:00'
[2024-10-21T02:39:54.721+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_etl_dag.py", line 19, in transform_data
    tickers = data['tickers']
KeyError: 'tickers'
[2024-10-21T02:39:54.760+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=crypto_tickers_etl, task_id=transform, execution_date=20240916T000000, start_date=20241021T023953, end_date=20241021T023954
[2024-10-21T02:39:54.800+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 713 for task transform ('tickers'; 402)
[2024-10-21T02:39:54.881+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-21T02:39:55.281+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
